# Generated by Django 4.1.2 on 2022-11-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_bodypart_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypart',
            name='icon',
        ),
    ]
