# Generated by Django 4.1.2 on 2022-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypart',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exercises',
            name='icon',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exercises',
            name='type',
            field=models.ManyToManyField(to='exercise.exercisetype'),
        ),
    ]
