# Generated by Django 4.1.2 on 2022-11-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_bodypart_icon_exercises_icon_exercises_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exercises', models.ManyToManyField(to='exercise.exercises')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercise.exercisetype')),
            ],
        ),
    ]
