# Generated by Django 4.1.2 on 2022-11-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('series1', models.CharField(max_length=10)),
                ('series2', models.CharField(max_length=10)),
                ('series3', models.CharField(max_length=10)),
                ('series4', models.CharField(max_length=10)),
                ('wage1', models.CharField(max_length=10)),
                ('wage2', models.CharField(max_length=10)),
                ('wage3', models.CharField(max_length=10)),
                ('wage4', models.CharField(max_length=10)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.exercises')),
            ],
        ),
    ]
