# Generated by Django 4.1.2 on 2022-11-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='series1',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='series2',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='series3',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='series4',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='wage1',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='wage2',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='wage3',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='wage4',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
